---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/agentgateway.dev/agentgatewaybackend_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: llm-backend-complex
spec:
  ai:
    provider:
      openai:
        model: deepseek-v4-pro
      host: &host api.deepseek.com
      port: 443
  policies:
    auth:
      secretRef:
        name: deepseek-credentials
    tls:
      sni: *host
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/agentgateway.dev/agentgatewaybackend_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: llm-backend-fast
spec:
  ai:
    provider:
      openai:
        model: deepseek-v4-flash
      host: &host api.deepseek.com
      port: 443
  policies:
    auth:
      secretRef:
        name: deepseek-credentials
    tls:
      sni: *host
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/agentgateway.dev/agentgatewaybackend_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: llm-backend-memory
spec:
  ai:
    provider:
      openai:
        model: "qwen3.5-4b"
      host: llama-qwen3.servitor-apps.svc.cluster.local
      port: 8080
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/agentgateway.dev/agentgatewaybackend_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: llm-backend-omni
spec:
  ai:
    provider:
      openai:
        model: "Qwen/Qwen3-Omni-30B-A3B-Instruct"
      host: &host api.siliconflow.cn
      port: 443
  policies:
    auth:
      secretRef:
        name: siliconflow-credentials
    tls:
      sni: *host
