---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/agentgateway.dev/agentgatewaypolicy_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: &name llm-api-auth
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: agentgateway-llm-route
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: agentgateway-media-route
  traffic:
    apiKeyAuthentication:
      mode: Strict
      secretRef:
        name: *name
