---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llm-api-auth
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # format: "sk-$(whoami)-$(openssl rand -hex 16)"
        api: |
          {
            "key": "{{ .agentgateway_api_auth }}",
            "metadata": {
              "user_id": "api"
            }
          }
  dataFrom:
    - extract:
        key: llm-api
