---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name toolhive-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: toolhive-operator

  values:
    operator:
      replicaCount: 1
      # cluster scope
      features:
        storageVersionMigrator: false
      rbac:
        scope: "namespace"
        allowedNamespaces:
          - "servitor-apps"
