---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firecrawl
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # LLM
        OPENAI_BASE_URL: "http://agentgateway-proxy.networking-system.svc.cluster.local:80/chat"
        OPENAI_MODEL_NAME: "omni"
        OPENAI_API_KEY: "{{ .agentgateway_api_auth }}"
  dataFrom:
    - extract:
        key: llm-api
