---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: &name mcp-victoria-logs
spec:
  groupRef:
    name: internal-ro
  image: ghcr.io/victoriametrics-community/mcp-victorialogs:v1.8.0@sha256:d2a0826def2b4a25f0e26c8d3e7f28f02117f90b6b4c99f2c354421f6dee30d1
  env:
    - name: VL_INSTANCE_ENTRYPOINT
      value: "http://victoria-logs-server.monitoring-system.svc.cluster.local:9428"
    - name: MCP_SERVER_MODE
      value: "http"
    - name: MCP_LISTEN_ADDR
      value: ":8081"
  mcpPort: 8081
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
