---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/tuppr.home-operations.com/kubernetesupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.37.0

  # defaults
  maintenance:
    windows:
      # Monday 01:00 - 05:00
      - start: "0 1 * * 1"
        duration: "4h"
        timezone: "Asia/Shanghai"
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        !(has(status.phase) && status.phase in ["Running", "Pending"])
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ["HEALTH_OK", "HEALTH_WARN"]
