---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.13.7

  # defaults
  maintenance:
    windows:
      # Sunday 01:00 - 05:00
      - start: "0 1 * * 0"
        duration: "4h"
        timezone: "Asia/Shanghai"
  parallelism: 1
  policy:
    force: false
    stage: false
    placement: soft
    rebootMode: default
  healthChecks:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      expr: |-
        status.conditions.filter(c, c.type == "Synchronizing").all(c, c.status == "False")
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK'] || status.ceph.health in ['HEALTH_WARN']
