---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # app
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  # utils
  - ./externalsecret.yaml
  - ./httproute.yaml
  - ./referencegrant.yaml
  # core blueprints
  - ./blueprints/core/basic-users.yaml
  # oidc blueprints
  - ./blueprints/oidc/grafana.yaml
  - ./blueprints/oidc/headlamp.yaml
  - ./blueprints/oidc/home-assistant.yaml
  - ./blueprints/oidc/immich.yaml
  - ./blueprints/oidc/jellyfin.yaml
  - ./blueprints/oidc/karakeep.yaml
  - ./blueprints/oidc/kavita.yaml
  - ./blueprints/oidc/netbox.yaml
  - ./blueprints/oidc/qbittorrent-ui.yaml
  - ./blueprints/oidc/stirling-pdf.yaml
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: "disabled"
  disableNameSuffixHash: false
configMapGenerator:
  - name: authentik-blueprints-core
    files:
      - ./blueprints/core/flow-authentication.yaml
      - ./blueprints/core/outpost-proxy.yaml
      - ./blueprints/core/policy-reputation.yaml
      - ./blueprints/core/scope-groups-mapping.yaml
      - ./blueprints/core/scope-groups.yaml
  - name: authentik-blueprints-forward
    files:
      - ./blueprints/forward/agentgateway.yaml
      - ./blueprints/forward/bambuddy.yaml
      - ./blueprints/forward/frigate.yaml
      - ./blueprints/forward/hermes-agent.yaml
      - ./blueprints/forward/hindsight.yaml
      - ./blueprints/forward/homepage.yaml
      - ./blueprints/forward/hubble.yaml
      - ./blueprints/forward/metube.yaml
      - ./blueprints/forward/miniflux.yaml
      - ./blueprints/forward/qbittorrent.yaml
      - ./blueprints/forward/rsshub.yaml
      - ./blueprints/forward/scrypted.yaml
      - ./blueprints/forward/sillytavern.yaml
      - ./blueprints/forward/victoria-logs.yaml
      - ./blueprints/forward/victoria-metrics.yaml
      - ./blueprints/forward/victoria-traces.yaml
      - ./blueprints/forward/z2m.yaml
