---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: document
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: music
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photo
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: video
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: synology-volume2
