---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: buzz-agent
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        BUZZ_PRIVATE_KEY: "{{ .agent_private_key }}"
        BUZZ_ACP_AGENT_OWNER: "{{ .admin_public_key }}"
        OPENAI_BASE_URL: http://agentgateway-proxy.networking-system.svc.cluster.local
        OPENAI_API_KEY: "{{ .agentgateway_api_auth }}"
  dataFrom:
    - extract:
        key: buzz
    - extract:
        key: llm-api
