---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name kgateway
spec:
  jobLabel: *name
  namespaceSelector:
    matchNames:
      - networking-system
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  endpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
