---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name openebs-localpv
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs-localpv

  values:
    fullnameOverride: *name
    global:
      imageRegistry: "quay.io"
    analytics:
      enabled: false
    hostpathClass:
      enabled: true
      name: openebs-hostpath
      isDefaultClass: false
    localpv:
      replicas: 2
      # Optional, use '/var/mnt/local-cache' with '20-mount-hostpath.yaml'
      basePath: /var/mnt/local-hostpath
