---
# schematic for production environment
# b7e0c94a9ed78c4d249cd4d53f177d2763d27350490ba29c2e7ac722493450a2
customization:
  bootloader: sd-boot
  extraKernelArgs:
    # stability
    - pcie_aspm=off
    - nvme_core.default_ps_max_latency_us=0
    # hardware
    - i915.enable_guc=3
    - module_blacklist=igc
  systemExtensions:
    officialExtensions:
      - siderolabs/i915
      - siderolabs/intel-ucode
      - siderolabs/mei
      - siderolabs/nut-client
      - siderolabs/kata-containers
