---
# schematic for production environment
# id is resolved live from factory.talos.dev and tracked in ../version.yaml
customization:
  bootloader: sd-boot
  extraKernelArgs:
    # stability
    - pcie_aspm=off
    - nvme_core.default_ps_max_latency_us=0
    # hardware
    - i915.enable_guc=3
    - module_blacklist=igc
  systemExtensions:
    officialExtensions:
      - siderolabs/i915
      - siderolabs/intel-ucode
      - siderolabs/kata-containers
      - siderolabs/mei
      - siderolabs/nut-client
