---
cluster:
  etcd:
    extraArgs:
      quota-backend-bytes: 8589934592
    advertisedSubnets:
      - 10.10.0.0/24
machine:
  features:
    nodeAddressSortAlgorithm:
  install:
    # renovate: datasource=github-releases depName=siderolabs/talos
    image: factory.talos.dev/metal-installer/88a80a46089706032472a6cb4ecbe8e19a6774d3520869dec3a203631eadbc21:v1.13.7
    grubUseUKICmdline: true
    diskSelector:
      model: "SQF-C3AV1-256GDEDM"
---
apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
  servers:
    - 10.10.0.254
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 10.10.0.254
searchDomains:
  disableDefault: true
hostDNS:
  resolveMemberNames: true
---
apiVersion: v1alpha1
kind: LinkConfig
name: kubedns-forward-host-fix
up: true
addresses:
  - address: 169.254.116.108/32
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: nut-client
configFiles:
  - content: |-
      MONITOR ups@10.10.0.254 1 monuser secret secondary
      SHUTDOWNCMD "/sbin/poweroff"
    mountPath: /usr/local/etc/nut/upsmon.conf
---
apiVersion: v1alpha1
kind: OOMConfig
triggerExpression: "false" # disable until 'MemAvailable' implemented
---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  diskSelector:
    match: system_disk
  maxSize: 80GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: local-hostpath
provisioning:
  diskSelector:
    match: system_disk
  maxSize: 140GiB
