{
 "title": "Envoy / Upstream",
 "description": "A dashboard that monitors Envoy with a focus on giving an upstreams. The dashboards were generated using [envoy-mixin](https://github.com/adinhodovic/envoy-mixin). Open issues and create feature requests in the repository.",
 "tags": [
  "envoy",
  "envoy-mixin",
  "gateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(envoy_cluster_upstream_rq_xx{}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_xx{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(envoy_cluster_upstream_rq_xx{cluster=\"$cluster\", namespace=~\"$namespace\"}, job)"
   },
   {
    "name": "envoy_cluster_name",
    "label": "Envoy Cluster Name",
    "query": "label_values(envoy_cluster_upstream_rq_xx{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}, envoy_cluster_name)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(envoy_cluster_upstream_rq_xx{cluster=\"$cluster\", namespace=~\"$namespace\", job=~\"$job\", envoy_cluster_name=~\"$envoy_cluster_name\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstreams Count by Job",
   "type": "piechart",
   "description": "The distribution of upstreams by job.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "upstreams" } },
   "targets": [
    {
     "expr": "count(\n  envoy_cluster_upstream_rq_total{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n  }\n) by (job)\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Upstream Rate by Envoy Cluster Name [1h]",
   "type": "piechart",
   "description": "The distribution of upstream request rates by Envoy cluster name.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_total{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n      }[1h]\n    )\n  ) by (envoy_cluster_name)\n)\n",
     "legendFormat": "{{ envoy_cluster_name }}"
    }
   ]
  },
  {
   "title": "Upstream Rate by Code Class [1h]",
   "type": "piechart",
   "description": "The distribution of upstream request rates by response code class.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n    }[1h]\n  )\n) by (envoy_response_code_class)\n",
     "legendFormat": "{{ envoy_response_code_class }}xx"
    }
   ]
  },
  {
   "title": "Upstream Active Connections by Envoy Cluster Name",
   "type": "piechart",
   "description": "The distribution of active upstream connections by Envoy cluster name.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20,\n  sum(\n    envoy_cluster_upstream_cx_active{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n    }\n  ) by (envoy_cluster_name)\n)\n",
     "legendFormat": "{{ envoy_cluster_name }}"
    }
   ]
  },
  { "title": "$envoy_cluster_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "envoy_cluster_name" },
  {
   "title": "Upstream Rate",
   "type": "timeseries",
   "description": "The upstream request rate by Envoy cluster name over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (envoy_cluster_name)\n",
     "legendFormat": "{{ envoy_cluster_name }}"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "description": "The upstream latency percentiles over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(\n    rate(\n      envoy_cluster_upstream_rq_time_bucket{\n        cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n      }[$__rate_interval]\n    )\n  ) by (le)\n)\n",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Upstream Success Rate (Excluding 4xx errors)",
   "type": "timeseries",
   "description": "The upstream success rate over time, counting 5xx response codes as errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n,\n      envoy_response_code_class!=\"5\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n)\n* 100\n",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Upstream Success Rate (Including 4xx errors)",
   "type": "timeseries",
   "description": "The upstream success rate over time, counting 4xx and 5xx response codes as errors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n,\n      envoy_response_code_class!~\"4|5\"\n    }[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n)\n* 100\n",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Upstream Rate by Code Class",
   "type": "timeseries",
   "description": "The upstream request rate by response code class over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_xx{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n\n    }[$__rate_interval]\n  )\n) by (envoy_response_code_class)\n",
     "legendFormat": "{{ envoy_response_code_class }}xx"
    }
   ]
  },
  {
   "title": "Upstream Rate by Code",
   "type": "timeseries",
   "description": "The upstream request rate by response code over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (envoy_response_code)\n",
     "legendFormat": "{{ envoy_response_code }}"
    }
   ]
  },
  {
   "title": "Upstream Healthy Percent",
   "type": "timeseries",
   "description": "The percentage of healthy upstream members by Envoy cluster name over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  envoy_cluster_membership_healthy{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n  }\n) by (job, envoy_cluster_name)\n/\nsum(\n  envoy_cluster_membership_total{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n  }\n) by (job, envoy_cluster_name)\n* 100\n",
     "legendFormat": "{{ envoy_cluster_name }}"
    }
   ]
  },
  {
   "title": "Upstream Connections",
   "type": "timeseries",
   "description": "The upstream connections over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  envoy_cluster_upstream_cx_active{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n  }\n) by (envoy_cluster_name)\n",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "sum(\n  increase(\n    envoy_cluster_upstream_cx_overflow{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Overflow Connections"
    },
    {
     "expr": "sum(\n  increase(\n    envoy_cluster_upstream_cx_destroy{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Destroyed Connections"
    },
    {
     "expr": "sum(\n  increase(\n    envoy_cluster_upstream_cx_connect_fail{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Connect Failures"
    }
   ]
  },
  {
   "title": "Upstream Circuit Breakers",
   "type": "timeseries",
   "description": "The upstream circuit breakers over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  envoy_cluster_circuit_breakers_default_cx_open{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n  }\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Open Connections"
    },
    {
     "expr": "sum(\n  envoy_cluster_circuit_breakers_default_cx_pool_open{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n  }\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Open Pool Connections"
    },
    {
     "expr": "sum(\n  envoy_cluster_circuit_breakers_default_rq_open{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n  }\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Open Requests"
    }
   ]
  },
  {
   "title": "Upstream Retry Rate",
   "type": "timeseries",
   "description": "The upstream retry rates over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_retry{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Retry Rate"
    },
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_retry_overflow{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Retry Overflow Rate"
    },
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_timeout{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (job, envoy_cluster_name)\n",
     "legendFormat": "Timeout Rate"
    }
   ]
  },
  {
   "title": "Upstream Rate by Pod",
   "type": "timeseries",
   "description": "The upstream request rate by pod over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    envoy_cluster_upstream_rq_total{\n      cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n    }[$__rate_interval]\n  )\n) by (pod, envoy_cluster_name)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Upstream Active Connections by Pod",
   "type": "timeseries",
   "description": "The upstream active connections by pod over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  envoy_cluster_upstream_cx_active{\n    cluster=\"$cluster\",\nnamespace=~\"$namespace\",\njob=~\"$job\",\npod=~\"$pod\"\n\n,\nenvoy_cluster_name=\"$envoy_cluster_name\"\n\n  }\n) by (pod, envoy_cluster_name)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}