---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name jellyfin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: gitops-system

  values:
    controllers:
      *name :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jellyfin/jellyfin
              tag: 10.11.11
            env:
              PUID: "2000"
              PGID: "2000"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - >
                        ls /media > /dev/null
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 15
                  failureThreshold: 5
                  successThreshold: 1
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
              limits:
                gpu.intel.com/i915: 1
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true

    service:
      app:
        ports:
          http:
            port: 8096
    route:
      app:
        hostnames: ["movie.noirprime.com"]
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: jellyfin.svg
          gethomepage.dev/name: Jellyfin
          gethomepage.dev/group: Media
          gethomepage.dev/widget.type: jellyfin
          gethomepage.dev/widget.url: http://jellyfin.media-apps.svc.cluster.local:8096
          gethomepage.dev/widget.key: '{{ "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}" }}' # yamllint disable-line rule:quoted-strings
          gethomepage.dev/widget.enableBlocks: "true"
          gethomepage.dev/widget.enableNowPlaying: "true"
          gethomepage.dev/widget.enableMediaControl: "false"
          gethomepage.dev/widget.showEpisodeNumber: "true"
          gethomepage.dev/widget.expandOneStreamToTwoRows: "true"
        parentRefs:
          - name: kgateway-internal
            namespace: networking-system

    persistence:
      app:
        existingClaim: *name
        globalMounts:
          - path: /config
      shared:
        existingClaim: video
        globalMounts:
          - path: /media
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /cache
            subPath: cache
          - path: /config/log
            subPath: log
          - path: /tmp
            subPath: tmp
