---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name clickhouse-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: clickhouse-operator

  values:
    certManager:
      enabled: true
    prometheus:
      enabled: true
