---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name buzz-relay
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # docker run --rm --entrypoint /usr/local/bin/buzz-admin ghcr.io/block/buzz:main generate-key
        BUZZ_RELAY_PRIVATE_KEY: "{{ .relay_private_key }}"
        BUZZ_GIT_HOOK_HMAC_SECRET: "{{ .git_hook_hmac_secret }}"
  dataFrom:
    - extract:
        key: buzz
