---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name kopiur
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: storage-system
  path: "./kubernetes/apps/storage-system/kopiur/app"
  wait: true
  dependsOn:
    - name: snapshot-controller
      namespace: storage-system
    - name: rook-ceph-cluster
      namespace: storage-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *name
      namespace: storage-system
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name kopiur-repository
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kopiur
  targetNamespace: storage-system
  path: "./kubernetes/apps/storage-system/kopiur/repository"
  wait: true
  dependsOn:
    - name: kopiur
      namespace: storage-system
