---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audiomuse
data:
  # : general
  TEMP_DIR: "/app/temp_audio"
  AUTH_ENABLED: "false"
  # : backend
  MEDIASERVER_TYPE: "navidrome"
  NAVIDROME_URL: "http://navidrome.media-apps.svc.cluster.local:4533"
  MUSIC_LIBRARIES: "/music"
  # : redis
  REDIS_URL: "redis://audiomuse-dragonfly.media-apps.svc.cluster.local:6379/0"
  # : postgres
  POSTGRES_DB: "audiomuse"
  POSTGRES_HOST: "postgres-rw.database-system.svc.cluster.local"
  POSTGRES_PORT: "5432"
