set quiet := true
set shell := ['bash', '-euo', 'pipefail', '-c']

controller := `talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1`
nodes := `talosctl config info -o yaml | yq -e '.nodes | join (" ")'`

[private]
default: talos kubernetes kubeconfig wait namespaces resources crds apps

# ! not finished yet ! #
