---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/clickhouse.com/clickhousecluster_v1alpha1.json
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: default
spec:
  replicas: 2
  shards: 1
  keeperClusterRef:
    name: default
  dataVolumeClaimSpec:
    storageClassName: ceph-block
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 100Gi
  podTemplate:
    topologyZoneKey: topology.kubernetes.io/zone
    nodeHostnameKey: kubernetes.io/hostname
    volumes:
      - name: init-db
        configMap:
          name: clickhouse-init-db
      - name: init-user
        secret:
          secretName: clickhouse-credentials
          items:
            - key: langfuse.yaml
              path: langfuse.yaml
  containerTemplate:
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    volumeMounts:
      - mountPath: /docker-entrypoint-initdb.d/
        name: init-db
        readOnly: true
      - mountPath: /etc/clickhouse-server/users.d/
        name: init-user
        readOnly: true
  settings:
    enableDatabaseSync: true
    defaultUserPassword:
      passwordType: plaintext_password
      secret:
        name: clickhouse-credentials
        key: default_password
