---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/toolhive.stacklok.dev/mcpremoteproxy_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPRemoteProxy
metadata:
  name: fast-note-sync
spec:
  groupRef:
    name: internal-rw
  remoteUrl: http://fast-note-sync.selfhosted-apps.svc.cluster.local:9000/api/mcp
  proxyPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
