---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name buzz-relay
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: buzz

  values:
    replicaCount: 1
    image:
      # renovate: datasource=docker depName=ghcr.io/block/buzz
      tag: "0.1.1"
    relayUrl: wss://buzz.noirprime.com
    service:
      annotations:
        lbipam.cilium.io/ips: "10.10.0.145"

    # admin_public_key
    ownerPubkey: "51128b278bea1a25c47128f6fe6811e8752837c119f67edc7fe0cdc3b7b2959a"

    secrets:
      existingSecret: *name
    relay:
      extraEnv:
        - name: BUZZ_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ceph-bucket-buzz-relay
              key: AWS_ACCESS_KEY_ID
        - name: BUZZ_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ceph-bucket-buzz-relay
              key: AWS_SECRET_ACCESS_KEY
    extraInitContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:18
        envFrom:
          - secretRef:
              name: buzz-relay-initdb
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
    persistence:
      git:
        enabled: false
    externalPostgresql:
      url: "postgresql://buzz-relay:buzz-relay@postgres-rw.database-system.svc.cluster.local:5432/buzz-relay"
    externalRedis:
      url: "redis://buzz-relay-dragonfly.servitor-apps.svc.cluster.local:6379"
    s3:
      endpoint: http://rook-ceph-rgw-ceph-objectstore.storage-system.svc.cluster.local
      bucket: *name
    serviceMonitor:
      enabled: true
