---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name rsshub
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/rsshub/app"
  dependsOn:
    - name: dragonfly-operator
      namespace: database-system
  components:
    - ../../../../components/authentik
    - ../../../../components/dragonfly
  postBuild:
    substitute:
      APP: *name
