---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name code-server
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: smarthome-apps
  path: "./kubernetes/apps/smarthome-apps/code-server/app"
  dependsOn:
    - name: home-assistant
      namespace: smarthome-apps
    - name: zigbee2mqtt
      namespace: smarthome-apps
  components:
    - ../../../../components/authentik
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *name
