---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name qbittorrent-ui
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: media-apps
  path: "./kubernetes/apps/media-apps/qbittorrent-ui/app"
  dependsOn:
    - name: media-nfs
      namespace: media-apps
  components:
    - ../../../../components/kopiur
  postBuild:
    substitute:
      APP: *name
