---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted-apps
components:
  - ../../components/namespace
  - ../../components/kopiur/secret
resources:
  - ./bambuddy/ks.yaml
  - ./dispatcharr/ks.yaml
  - ./fast-note-sync/ks.yaml
  - ./firecrawl/ks.yaml
  - ./hindsight/ks.yaml
  - ./homepage/ks.yaml
  - ./karakeep/ks.yaml
  - ./miniflux/ks.yaml
  - ./netbox/ks.yaml
  - ./open-notebook/ks.yaml
  - ./rsshub/ks.yaml
  - ./searxng/ks.yaml
  - ./sillytavern/ks.yaml
  - ./stirling-pdf/ks.yaml
