---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/agentgateway.dev/agentgatewayparameters_v1alpha1.json
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayParameters
metadata:
  name: agentgateway-params
spec:
  deployment:
    spec:
      replicas: 2
      template:
        spec:
          containers:
            - name: agentgateway
              ports:
                - name: metrics
                  containerPort: 15020
                  protocol: TCP
                - name: ui
                  containerPort: 15000
                  protocol: TCP
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app: agentgateway
  podDisruptionBudget:
    spec:
      minAvailable: 1
  rawConfig:
    config:
      adminAddr: 0.0.0.0:15000
  service:
    spec:
      ports:
        - port: 15000
          name: portal
          targetPort: 15000
          protocol: TCP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
