---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &name agentgateway-proxy
spec:
  jobLabel: *name
  namespaceSelector:
    matchNames:
      - networking-system
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      honorLabels: true
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
