---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name mcp-fast-note-sync
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: servitor-apps
  path: "./kubernetes/apps/servitor-apps/mcp/fast-note-sync/app"
  dependsOn:
    - name: toolhive-config
      namespace: servitor-apps
    - name: fast-note-sync
      namespace: selfhosted-apps
