set quiet := true
set shell := ['bash', '-euo', 'pipefail', '-c']

TALOS_ENDPOINT := `talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1`

[private]
default:
  @just --list

[doc('Get latest secureboot ISO for talos, with https_proxy support')]
image mode:
  #!/usr/bin/env bash
  IMAGE_VERSION=$(curl --silent --noproxy '*' https://factory.talos.dev/versions \
    | jq --raw-output 'map(select(test("^v[0-9.]+$"))) | sort_by(. | ltrimstr("v") | split(".") | map(tonumber)) | reverse | .[0]' \
    | tail -n1)
  IMAGE_SCHEMA=$(just _schema {{mode}})
  echo "Latest version: ${IMAGE_VERSION}"
  echo "Image Downloading: talos-{{mode}}-${IMAGE_VERSION}-metal-amd64-secureboot.iso"
  curl -x "${https_proxy}" --progress-bar -L "https://factory.talos.dev/image/${IMAGE_SCHEMA}/${IMAGE_VERSION}/metal-amd64-secureboot.iso" \
    -o "/tmp/talos-{{mode}}-${IMAGE_VERSION}-metal-amd64-secureboot.iso"
  mv "/tmp/talos-{{mode}}-${IMAGE_VERSION}-metal-amd64-secureboot.iso" "${OPS_DIR}"

[doc('Get schema ID for specific environment')]
_schema mode:
  yq '.controlPlane.schematic' "${TALOS_DIR}/talconfig.{{mode}}.yaml" > /tmp/schematic.yaml
  curl --silent --noproxy '*' -X POST --data-binary @/tmp/schematic.yaml https://factory.talos.dev/schematics | jq --raw-output '.id'

[doc('Generate talos configuration')]
generate mode:
  op run --env-file "${TALOS_DIR}/talhelper.env" --no-masking -- talhelper genconfig \
      --config-file "${TALOS_DIR}/talconfig.{{mode}}.yaml" \
      --secret-file "${TALOS_DIR}/talsecret.yaml" \
      --out-dir "${TALOS_DIR}/clusterconfig"
  mkdir -p ~/.talos && cp "${TALOSCONFIG}" ~/.talos/config

[doc('Apply talos configuration to node')]
apply node *args:
  @echo "Applying talos configuration to {{node}}"
  talosctl apply-config --nodes {{node}} --file ${TALOS_DIR}/clusterconfig/main-{{node}}.yaml {{args}}

[doc('Bootstrap talos cluster, INSECURE')]
_bootstrap_talos:
  #!/usr/bin/env bash
  for FILE in $(ls ${TALOS_DIR}/clusterconfig/*.yaml); do \
    NODE_IP=$(basename "$FILE" .yaml | sed 's/^main-//')
    echo "🚀 Bootstrapping Talos Node: $NODE_IP"
    count=0
    until talosctl apply-config --nodes "$NODE_IP" --file "$FILE" --insecure 2>/dev/null; do
      exit_code=$?
      count=$((count + 1))
      if [ $count -ge 5 ]; then
          echo "⚠️ Failed to apply config to $NODE_IP after 5 attempts. Assuming node might be rebooting or already ready. Continuing..."
          break
      fi
      echo "⏳ Waiting for $NODE_IP to accept config (Attempt $count/5)..."
      sleep 3
    done
  done

[doc('Bootstrap K8S')]
_bootstrap_k8s:
  #!/usr/bin/env bash
  echo "🔍 Checking if cluster is already bootstrapped..."
  ETCD_STATUS=$(talosctl -n "{{TALOS_ENDPOINT}}" get service etcd -o json 2>/dev/null | jq -r '.spec.running' || echo "false")
  if [ "$ETCD_STATUS" == "true" ]; then
    echo "✅ Etcd is Running. Cluster implies bootstrapped. Skipping."
    exit 0
  fi
  echo "🚀 Etcd running status is '${ETCD_RUNNING}'. Attempting bootstrap..."
  count=0
  until talosctl -n "{{TALOS_ENDPOINT}}" bootstrap 2>&1 | grep -E "AlreadyExists|No error"|| [ "$count" -ge 12 ]; do
    echo "⏳ Sending bootstrap command (Attempt $((++count))/12)..."
        sleep 5
    done
    FINAL_RUNNING=$(talosctl -n "{{TALOS_ENDPOINT}}" get service etcd -o json 2>/dev/null | jq -r '.spec.running' || echo "false")
    if [ "$FINAL_RUNNING" == "true" ]; then
       echo "✅ Bootstrap successful (Etcd is running)."
       exit 0
    else
       if [ "$count" -ge 12 ]; then
           echo "❌ Failed to bootstrap cluster. Etcd is not running."
           exit 1
       fi
    fi

[doc('Fetch kubeconfig')]
kubeconfig:
  #!/usr/bin/env bash
  function retry {
    local retries=$1
    shift
    local count=0
    until "$@"; do
        exit_code=$?
        count=$((count + 1))
        if [ $count -ge $retries ]; then
            echo "❌ Command failed after $retries attempts: $*"
            return $exit_code
        fi
        echo "⚠️  Connection failed. Retrying in 5s... ($count/$retries)"
        sleep 5
    done
    return 0
  }
  retry 20 timeout 5 bash -c "</dev/tcp/{{ TALOS_ENDPOINT }}/6443" 2>/dev/null
  talosctl kubeconfig --nodes {{ TALOS_ENDPOINT }} --force "${KUBECONFIG}"
  mkdir -p ~/.kube && cp "${KUBECONFIG}" ~/.kube/config

[doc('Reboot node')]
reboot node:
  #!/usr/bin/env bash
  printf "Reboot node {{node}}? (y/N) "
  read -r confirm
  case "$confirm" in
    y|Y)
      talosctl -n {{node}} reboot -m powercycle
      ;;
    *)
      echo "Cancelled."
      exit 0
      ;;
  esac

[doc('Reset node or cluster')]
reset node:
  #!/usr/bin/env bash
  printf "Reset {{node}}? (y/N) "
  read -r confirm
  case "$confirm" in
    y|Y)
      if [ "{{node}}" = "cluster" ]; then
        talosctl reset --system-labels-to-wipe STATE \
          --system-labels-to-wipe EPHEMERAL \
          --graceful=false --wait=false --reboot
      else
        talosctl -n {{node}} reset --graceful=false --reboot
      fi
      ;;
    *)
      echo "Cancelled."
      exit 0
      ;;
  esac
