---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name onyx
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # openssl rand -hex 32
        USER_AUTH_SECRET: "{{ .user_auth_secret }}"
        # must meet OpenSearch complexity: >=8 chars, upper+lower+digit+special
        OPENSEARCH_ADMIN_USERNAME: "admin"
        OPENSEARCH_ADMIN_PASSWORD: "{{ .opensearch_admin_password }}"
  dataFrom:
    - extract:
        key: *name
