---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
data:
  IMMICH_ENV: production
  IMMICH_LOG_LEVEL: log
  REDIS_HOSTNAME: immich-dragonfly.media-apps.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
