---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name rook-ceph-drivers
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ceph-csi-drivers

  values:
    drivers:
      rbd:
        name: storage-system.rbd.csi.ceph.com
      nvmeof:
        name: storage-system.nvmeof.csi.ceph.com
      cephfs:
        name: storage-system.cephfs.csi.ceph.com
      nfs:
        name: storage-system.nfs.csi.ceph.com
