---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: ceph-csi-drivers
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.0.4
  url: oci://ghcr.io/soulwhisper/charts/ceph-csi-drivers
