---
name: talos

# meshcentral listens on port 4433 (AMT) and 444 (https)

services:
  talos-api:
    image: "ghcr.io/siderolabs/discovery-service:v1.1.1"
    container_name: "talos-api"
    restart: "unless-stopped"
    ports:
      - "9300:3000/tcp"

  meshcentral:
    image: "ghcr.io/ylianst/meshcentral:1.2.5"
    container_name: "meshcentral"
    restart: "unless-stopped"
    network_mode: "host"
    configs:
      - source: "config.json"
        target: "/opt/meshcentral/meshcentral-data/config.json"
    volumes:
      - "/volume3/docker/meshcentral/data:/opt/meshcentral/meshcentral-data"

configs:
  config.json:
    content: |
      { "settings": { "agentTimeStampServer": false }, "domains": { "": { "allowedOrigin": true } } }
