---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name external-secrets
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-secrets

  values:
    installCRDs: true
    replicaCount: 2
    leaderElect: true
    image:
      repository: ghcr.io/external-secrets/external-secrets
    resources:
      requests: { cpu: 10m, memory: 64Mi }
      limits: { memory: 256Mi }
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    serviceMonitor:
      enabled: true
      interval: 1m
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
    webhook:
      replicaCount: 2
      image:
        repository: ghcr.io/external-secrets/external-secrets
      resources:
        requests: { cpu: 10m, memory: 32Mi }
        limits: { memory: 128Mi }
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      serviceMonitor:
        enabled: true
        interval: 1m
