---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langfuse
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        LANGFUSE_INIT_USER_EMAIL: "{{ .admin_email }}"
        LANGFUSE_INIT_USER_NAME: "{{ .admin_user }}"
        LANGFUSE_INIT_USER_PASSWORD: "{{ .admin_pass }}"
        ENCRYPTION_KEY: "{{ .langfuse_encryption_key }}"
        NEXTAUTH_SECRET: "{{ .langfuse_secret }}"
        SALT: "{{ .langfuse_salt }}"
        CLICKHOUSE_PASSWORD: "{{ .langfuse_password }}"
  dataFrom:
    - extract:
        key: app-user
    - extract:
        key: encryption_cipher
    - extract:
        key: clickhouse
