---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media-apps
components:
  - ../../components/namespace
  - ../../components/kopiur/secret
resources:
  # storage
  - ./media-nfs/ks.yaml
  # app
  - ./jellyfin/ks.yaml
  - ./immich/ks.yaml
  - ./kavita/ks.yaml
  - ./metube/ks.yaml
  - ./moviepilot/ks.yaml
  - ./navidrome/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qbittorrent-ui/ks.yaml
