---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name netbox
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: netbox

  values:
    fullnameOverride: *name
    timeZone: "Asia/Shanghai"
    superuser:
      existingSecret: *name
    extraConfig:
      - values:
          REMOTE_AUTH_ENABLED: "True"
          REMOTE_AUTH_BACKEND: "social_core.backends.open_id_connect.OpenIdConnectAuth"
          REMOTE_AUTH_AUTO_CREATE_USER: "True"
          SOCIAL_AUTH_OIDC_ENDPOINT: "https://auth.noirprime.com/application/o/netbox/"
          SOCIAL_AUTH_OIDC_SCOPE: "openid profile email roles"
          LOGOUT_REDIRECT_URL: "https://auth.noirprime.com/application/o/netbox/end-session/"
          SOCIAL_AUTH_PIPELINE:
            [
              "social_core.pipeline.social_auth.social_details",
              "social_core.pipeline.social_auth.social_uid",
              "social_core.pipeline.social_auth.auth_allowed",
              "social_core.pipeline.social_auth.social_user",
              "social_core.pipeline.user.get_username",
              "social_core.pipeline.social_auth.associate_by_email",
              "social_core.pipeline.user.create_user",
              "social_core.pipeline.social_auth.associate_user",
              "social_core.pipeline.social_auth.load_extra_data",
              "social_core.pipeline.user.user_details",
              "netbox.sso_pipeline_roles.set_roles",
            ]
    extraEnvs:
      - name: SOCIAL_AUTH_OIDC_KEY
        valueFrom:
          secretKeyRef:
            name: *name
            key: oidc_client_id
      - name: SOCIAL_AUTH_OIDC_SECRET
        valueFrom:
          secretKeyRef:
            name: *name
            key: oidc_client_secret
    extraVolumes:
      - name: sso-pipeline-roles
        configMap:
          name: *name
    extraVolumeMounts:
      - name: sso-pipeline-roles
        mountPath: /opt/netbox/netbox/netbox/sso_pipeline_roles.py
        subPath: sso_pipeline_roles.py
        readOnly: true
    postgresql:
      enabled: false
    externalDatabase:
      host: postgres-rw.database-system.svc.cluster.local
      database: *name
      username: *name
      existingSecretName: netbox-pguser
      existingSecretKey: password
    initContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:18
        envFrom:
          - secretRef:
              name: netbox-initdb
    valkey:
      enabled: false
    tasksDatabase:
      host: &redis netbox-dragonfly.selfhosted-apps.svc.cluster.local
    cachingDatabase:
      host: *redis
    persistence:
      existingClaim: *name
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    # cronjob is deprecated
    housekeeping:
      enabled: false
    # fix stuck at 'init'
    updateStrategy:
      type: Recreate
    worker:
      updateStrategy:
        type: Recreate
    # below is the reason using official chart
    image:
      repository: ghcr.io/soulwhisper/netbox
      tag: 4.6.7
    plugins:
      - netbox_attachments
      - netbox_bgp
      - netbox_floorplan
      - netbox_interface_synchronization
      - netbox_dns
      - netbox_prometheus_sd
      - netbox_qrcode
      - netbox_reorder_rack
      - netbox_topology_views
    #   - netbox_napalm_plugin
    # pluginsConfig:
    #   netbox_napalm_plugin:
    #     NAPALM_USERNAME:
    #       valueFrom:
    #         secretKeyRef:
    #           name: *name
    #           key: NAPALM_USERNAME
    #     NAPALM_PASSWORD:
    #       valueFrom:
    #         secretKeyRef:
    #           name: *name
    #           key: NAPALM_PASSWORD
