---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # General
        NEXTAUTH_SECRET: "{{ .karakeep }}"
        MEILI_MASTER_KEY: "{{ .meilisearch }}"
        # LLM
        OPENAI_BASE_URL: "http://agentgateway-proxy.networking-system.svc.cluster.local:80/chat"
        OPENAI_API_KEY: "{{ .agentgateway_api_auth }}"
        INFERENCE_TEXT_MODEL: "fast"
        INFERENCE_IMAGE_MODEL: "vision"
        # OIDC
        OAUTH_CLIENT_ID: "{{ .karakeep_oidc_client_id }}"
        OAUTH_CLIENT_SECRET: "{{ .karakeep_oidc_client_secret }}"
  dataFrom:
    - extract:
        key: encryption_cipher
    - extract:
        key: llm-api
    - extract:
        key: authentik
