---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name agentgateway-crds
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/agentgateway/crds"
  wait: true
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name agentgateway
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/agentgateway/app"
  wait: true
  dependsOn:
    - name: agentgateway-crds
      namespace: networking-system
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name agentgateway-config
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: agentgateway
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/agentgateway/config/gateway"
  wait: true
  dependsOn:
    - name: agentgateway
      namespace: networking-system
    - name: onepassword-connect
      namespace: security-system
    - name: opentelemetry-collector
      namespace: monitoring-system
  components:
    - ../../../../../components/authentik # deeper than usual
  postBuild:
    substitute:
      APP: *name
      APP_ROUTE: agentgateway-dashboard
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name agentgateway-backend-llm
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: agentgateway
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/agentgateway/config/llm"
  dependsOn:
    - name: agentgateway-config
      namespace: networking-system
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agentgateway-backend-media
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: agentgateway
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/agentgateway/config/media"
  dependsOn:
    - name: agentgateway-config
      namespace: networking-system
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name agentgateway-backend-mcp
  annotations:
    config.home-ops.io/managed: "true"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: agentgateway
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/agentgateway/config/mcp"
  dependsOn:
    - name: agentgateway-config
      namespace: networking-system
    - name: toolhive-config
      namespace: servitor-apps
