---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: &name mcp-firecrawl
spec:
  groupRef:
    name: external
  image: ghcr.io/firecrawl/firecrawl-mcp-server:latest@sha256:53730c3bb4fd40841b7c5a1bfba0efb3a38514b09d9f73cb2d04277b57f011df
  env:
    - name: PORT
      value: "3000"
    - name: FIRECRAWL_API_URL
      value: "http://firecrawl.selfhosted-apps.svc.cluster.local:3002"
    - name: HTTP_STREAMABLE_SERVER
      value: "true"
  mcpPort: 3000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
