---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: &name mcp-firecrawl
spec:
  groupRef:
    name: external
  image: ghcr.io/firecrawl/firecrawl-mcp-server:latest
  env:
    - name: PORT
      value: &port 3000
    - name: FIRECRAWL_API_URL
      value: "http://firecrawl.selfhosted-apps.svc.cluster.local:3002"
    - name: FIRECRAWL_RETRY_MAX_ATTEMPTS
      value: "10"
    - name: FIRECRAWL_RETRY_INITIAL_DELAY
      value: "500"
    - name: TTP_STREAMABLE_SERVER
      value: "true"
  mcpPort: *port
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
