---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: &name mcp-firecrawl
spec:
  groupRef:
    name: external
  image: ghcr.io/firecrawl/firecrawl-mcp-server:latest@sha256:6f5619f53034ec01732c0ada4442fcb563f91ab7f8eeed9b0dee8c85222f7a97
  env:
    - name: PORT
      value: "3000"
    - name: FIRECRAWL_API_URL
      value: "http://firecrawl.selfhosted-apps.svc.cluster.local:3002"
    - name: HTTP_STREAMABLE_SERVER
      value: "true"
  mcpPort: 3000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
