---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitor-apps
components:
  - ../../components/namespace
resources:
  # system
  - ./llama/ks.yaml
  - ./toolhive/ks.yaml
  # mcp
  - ./mcp
  # app
  - ./agent-memory/ks.yaml
  - ./buzz/ks.yaml
  - ./hermes-agent/ks.yaml
