---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: servitor-apps
components:
  - ../../components/namespace
  - ../../components/kopiur/secret
resources:
  # system
  - ./toolhive/ks.yaml
  # mcp
  - ./mcp
  # app
  - ./hermes-agent/ks.yaml
  - ./onyx/ks.yaml
