---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/gateway.kgateway.dev/gatewayextension_v1alpha1.json
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: authentik-ext-auth
spec:
  extAuth:
    httpService:
      backendRef:
        name: authentik-server
        namespace: security-system
        port: 9000
      pathPrefix: "/outpost.goauthentik.io/auth/envoy"
      authorizationRequest:
        headersToAdd:
          x-forwarded-host: "%REQ(:authority)%"
          x-forwarded-proto: "%PROTOCOL%"
      authorizationResponse:
        headersToBackend:
          - "x-authentik-username"
          - "x-authentik-groups"
          - "x-authentik-email"
          - "x-authentik-name"
          - "x-authentik-uid"
          - "set-cookie"
