---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/gateway.kgateway.dev/listenerpolicy_v1alpha1.json
apiVersion: gateway.kgateway.dev/v1alpha1
kind: ListenerPolicy
metadata:
  name: default-listener-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kgateway-internal
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kgateway-external
  default:
    httpSettings:
      streamIdleTimeout: 0s
      upgradeConfig:
        enabledUpgrades:
          - websocket
      tracing:
        provider:
          openTelemetry:
            serviceName: kgateway
            grpcService:
              backendRef:
                name: opentelemetry-collector
                namespace: monitoring-system
                port: 4317
        spawnUpstreamSpan: true
        clientSampling: 100
        randomSampling: 100
        overallSampling: 100
        attributes:
          - name: enduser.id
            requestHeader:
              name: X-Authentik-Username
          - name: enduser.email
            requestHeader:
              name: X-Authentik-Email
          - name: enduser.scope
            requestHeader:
              name: X-Authentik-Groups
          - name: http.route.gateway
            literal:
              value: kgateway
