---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hermes-agent-dashboard
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: si-hermes
    gethomepage.dev/name: HermesBoard
    gethomepage.dev/group: Service
spec:
  hostnames: ["hermes.noirprime.com"]
  parentRefs:
    - name: kgateway-internal
      namespace: networking-system
  rules:
    - backendRefs:
        - name: hermes-agent
          namespace: servitor-apps
          port: 9119
