---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaming-apps
components:
  - ../../components/namespace
  - ../../components/kopiur/secret
resources:
  # ref: https://github.com/joryirving/home-ops/tree/main/kubernetes/apps/base/games
  # storage
  - ./gaming-nfs/ks.yaml
  # app
  - ./crafty-controller/ks.yaml
  - ./foundryvtt/ks.yaml
