---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: victoria-metrics-cluster
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        PUSHOVER_TOKEN: "{{ .pushover_token }}"
        PUSHOVER_USER_KEY: "{{ .pushover_key }}"
  dataFrom:
    - extract:
        key: pushover
