---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: code-server
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # home-assistant
        HASS_SERVER: "http://home-assistant.smarthome-apps.svc.cluster.local:8123"
        HASS_TOKEN: "{{ .supervisor_token }}"
  dataFrom:
    - extract:
        key: home-assistant
