---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name honcho
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/honcho/app"
  wait: true
  dependsOn:
    - name: cnpg-cluster
      namespace: database-system
    - name: dragonfly-operator
      namespace: database-system
    - name: llama
      namespace: servitor-apps
  components:
    - ../../../../components/cnpg
    - ../../../../components/dragonfly
  postBuild:
    substitute:
      APP: *name
---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name honcho-worker
  annotations:
    config.home-ops.io/managed: "true"
  labels:
    config.home-ops.io/deps: "infra"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: selfhosted-apps
  path: "./kubernetes/apps/selfhosted-apps/honcho/worker"
  dependsOn:
    - name: honcho
      namespace: selfhosted-apps
