---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        WOODPECKER_ADMIN: "{{ .woodpecker_admin }}"
        # forgejo
        WOODPECKER_FORGEJO: "true"
        WOODPECKER_FORGEJO_URL: "http://nas.homelab.internal:9003"
        WOODPECKER_FORGEJO_CLIENT: "{{ .woodpecker_client }}"
        WOODPECKER_FORGEJO_SECRET: "{{ .woodpecker_secret }}"
  dataFrom:
    - extract:
        key: forgejo
