---
# yaml-language-server: $schema=https://soulwhisper.github.io/k8s-schemas/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firecrawl-database
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        POSTGRES_PASSWORD: "{{ .firecrawl_nuq }}"
        NUQ_DATABASE_URL: "postgresql://postgres:{{ .firecrawl_nuq }}@firecrawl-database.selfhosted-apps.svc.cluster.local:5432/postgres"
  dataFrom:
    - extract:
        key: encryption_cipher
